server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost/postgres}
    username: postgres
    password: postgres

  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
user:
  userName: admin
  password: admin

role:
  roles: ADMIN,USER