version: '3'
services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile.development
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - "db-data:/var/lib/postgresql/data"


  app:
    build:
      context: app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/vv
      - JS_URL=http://localhost
    image: 'my-java-application'
    ports:
      - 8091:8091
    depends_on:
      - postgres